services:
  bootstrapbugz-api:
    container_name: bootstrapbugz-api
    image: bootstrapbugz-api:1.0.0
    build:
      context: ./backend/spring-boot
      dockerfile: Dockerfile
    ports:
      - "${EXPOSED_SERVER_PORT:-8081}:${SERVER_PORT:-8080}"
    environment:
      APP_NAME: ${APP_NAME:-BootstrapBugZ}
      SERVER_PORT: ${SERVER_PORT:-8080}
      UI_URL: ${UI_URL:-http://bootstrapbugz-ui:5173}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DATABASE:-bootstrapbugz}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-root}
      SPRING_DATA_REDIS_DATABASE: ${REDIS_DATABASE:-0}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT:-6379}
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD:-root}
      SPRING_SECURITY_USER_PASSWORD: ${SPRING_SECURITY_PASSWORD:-qwerty123}
      SPRING_MAIL_HOST: ${MAIL_HOST:-smtp.mailgun.org}
      SPRING_MAIL_PORT: ${MAIL_PORT:-587}
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME:-username}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD:-password}
      JWT_SECRET: ${JWT_SECRET:-secret}
    depends_on:
      - postgres
      - redis
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "${HTTP_PROTOCOL:-http}://localhost:${SERVER_PORT:-8080}/actuator/health",
        ]
      start_period: 10s
      interval: 30s
      retries: 3

  postgres:
    container_name: postgres
    image: postgres:17.2-alpine
    ports:
      - "${EXPOSED_POSTGRES_PORT:-5433}:${POSTGRES_PORT:-5432}"
    environment:
      PGPORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DATABASE:-bootstrapbugz}
      POSTGRES_USER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USERNAME:-postgres}",
          "-d",
          "${POSTGRES_DATABASE:-bootstrapbugz}",
        ]
      start_period: 10s
      interval: 30s
      retries: 3

  redis:
    container_name: redis
    image: redis:7.4.1
    ports:
      - "${EXPOSED_REDIS_PORT:-6380}:${REDIS_PORT:-6379}"
    command: redis-server --port ${REDIS_PORT:-6379} --requirepass ${REDIS_PASSWORD:-root}
    environment:
      REDIS_DATABASE: ${REDIS_DATABASE:-0}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-root}
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-h",
          "localhost",
          "-p",
          "${REDIS_PORT:-6379}",
          "-a",
          "${REDIS_PASSWORD:-root}",
          "ping",
        ]
      start_period: 10s
      interval: 30s
      retries: 3

  bootstrapbugz-ui:
    container_name: bootstrapbugz-ui
    image: bootstrapbugz-ui:1.0.0
    build:
      context: ./frontend/svelte-kit
      dockerfile: Dockerfile
    environment:
      PUBLIC_APP_NAME: ${APP_NAME:-BootstrapBugZ}
      PUBLIC_API_URL: ${API_URL:-http://bootstrapbugz-api:8080/v1}
      JWT_SECRET: ${JWT_SECRET:-secret}
    ports:
      - "${EXPOSED_UI_PORT:-5174}:${UI_PORT:-5173}"
    depends_on:
      - bootstrapbugz-api
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "${HTTP_PROTOCOL:-http}://localhost:${UI_PORT:-5173}",
        ]
      start_period: 10s
      interval: 30s
      retries: 3
