services:
  bootstrapbugz-api:
    container_name: bootstrapbugz-api
    image: "bootstrapbugz-api:1.0.0"
    build: .
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/${POSTGRES_DATABASE:-bootstrapbugz}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-root}
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST:-redis}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT:-6379}
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD:-root}
    depends_on:
      - postgres
      - redis
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "${PROTOCOL:-http}://localhost:8080/actuator/health",
        ]
      start_period: 10s
      interval: 30s
      retries: 3

  postgres:
    container_name: postgres
    image: "postgres:17.2-alpine"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE:-bootstrapbugz}
      POSTGRES_USER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "postgres",
          "-d",
          "${POSTGRES_DATABASE:-bootstrapbugz}",
        ]
      start_period: 10s
      interval: 30s
      retries: 3

  redis:
    container_name: redis
    image: "redis:7.4.1"
    ports:
      - "6380:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-root}
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-h",
          "localhost",
          "-a",
          "${REDIS_PASSWORD:-root}",
          "ping",
        ]
      start_period: 10s
      interval: 30s
      retries: 3

  bootstrapbugz-ui:
    container_name: bootstrapbugz-ui
    image: "bootstrapbugz-ui:1.0.0"
    build:
      context: ./frontend/svelte-kit
      dockerfile: Dockerfile
    env_file:
      - ./frontend/svelte-kit/.env
    ports:
      - "5174:5173"
    depends_on:
      - bootstrapbugz-api
    healthcheck:
      test: ["CMD", "curl", "-f", "${PROTOCOL:-http}://localhost:5173"]
      start_period: 10s
      interval: 30s
      retries: 3
