services:
  postgres:
    container_name: postgres
    image: postgres:17.2-alpine
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    environment:
      PGPORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DATABASE:-bootstrapbugz}
      POSTGRES_USER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USERNAME:-postgres}",
          "-d",
          "${POSTGRES_DATABASE:-bootstrapbugz}",
        ]
      start_period: 10s
      interval: 30s
      retries: 3

  redis:
    container_name: redis
    image: redis:7.4.1
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    command: redis-server --port ${REDIS_PORT:-6379} --requirepass ${REDIS_PASSWORD:-root}
    environment:
      REDIS_DATABASE: ${REDIS_DATABASE:-0}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-root}
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-h",
          "localhost",
          "-p",
          "${REDIS_PORT:-6379}",
          "-a",
          "${REDIS_PASSWORD:-root}",
          "ping",
        ]
      start_period: 10s
      interval: 30s
      retries: 3
