services:
  bugzkit-api:
    container_name: bugzkit-api
    image: bugzkit-api:1.0.0
    build:
      target: ${PROFILE:-dev}
    ports:
      - "${API_PORT:-8080}:${API_PORT:-8080}"
    environment:
      APP_NAME: ${APP_NAME:-bugzkit}
      API_PORT: ${API_PORT:-8080}
      UI_URL: ${HTTP_PROTOCOL:-http}://${UI_HOST:-localhost}:${UI_PORT:-5173}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DATABASE:-bugzkit}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-root}
      SPRING_DATA_REDIS_DATABASE: ${REDIS_DATABASE:-0}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT:-6379}
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD:-root}
      SPRING_SECURITY_USER_PASSWORD: ${SPRING_SECURITY_PASSWORD:-qwerty123}
      SPRING_MAIL_HOST: ${MAIL_HOST:-smtp.mailgun.org}
      SPRING_MAIL_PORT: ${MAIL_PORT:-587}
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME:-username}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD:-password}
      JWT_SECRET: ${JWT_SECRET:-secret}
    depends_on:
      - postgres
      - redis
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "${HTTP_PROTOCOL:-http}://localhost:${API_PORT:-8080}/actuator/health",
        ]
      start_period: 10s
      interval: 30s
      retries: 3

  postgres:
    container_name: postgres
    image: postgres:17.2-alpine
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    environment:
      PGPORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DATABASE:-bugzkit}
      POSTGRES_USER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USERNAME:-postgres}",
          "-d",
          "${POSTGRES_DATABASE:-bugzkit}",
        ]
      start_period: 10s
      interval: 30s
      retries: 3

  redis:
    container_name: redis
    image: redis:7.4.1
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    command: redis-server --port ${REDIS_PORT:-6379} --requirepass ${REDIS_PASSWORD:-root}
    environment:
      REDIS_DATABASE: ${REDIS_DATABASE:-0}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-root}
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-h",
          "localhost",
          "-p",
          "${REDIS_PORT:-6379}",
          "-a",
          "${REDIS_PASSWORD:-root}",
          "ping",
        ]
      start_period: 10s
      interval: 30s
      retries: 3
