export interface ErrorMessage {
  timestamp: Date;
  status: number;
  error: string;
  codes: ErrorCode[];
}

export enum ErrorCode {
  API_ERROR_AUTH_UNAUTHORIZED = 'API_ERROR_AUTH_UNAUTHORIZED',
  API_ERROR_AUTH_FORBIDDEN = 'API_ERROR_AUTH_FORBIDDEN',
  API_ERROR_AUTH_TOKEN_REQUIRED = 'API_ERROR_AUTH_TOKEN_REQUIRED',
  API_ERROR_AUTH_TOKEN_INVALID = 'API_ERROR_AUTH_TOKEN_INVALID',
  API_ERROR_USER_USERNAME_REQUIRED = 'API_ERROR_USER_USERNAME_REQUIRED',
  API_ERROR_USER_USERNAME_INVALID = 'API_ERROR_USER_USERNAME_INVALID',
  API_ERROR_USER_USERNAME_EXISTS = 'API_ERROR_USER_USERNAME_EXISTS',
  API_ERROR_USER_USERNAME_OR_EMAIL_REQUIRED = 'API_ERROR_USER_USERNAME_OR_EMAIL_REQUIRED',
  API_ERROR_USER_USERNAME_OR_EMAIL_INVALID = 'API_ERROR_USER_USERNAME_OR_EMAIL_INVALID',
  API_ERROR_USER_EMAIL_REQUIRED = 'API_ERROR_USER_EMAIL_REQUIRED',
  API_ERROR_USER_EMAIL_INVALID = 'API_ERROR_USER_EMAIL_INVALID',
  API_ERROR_USER_EMAIL_EXISTS = 'API_ERROR_USER_EMAIL_EXISTS',
  API_ERROR_USER_PASSWORD_REQUIRED = 'API_ERROR_USER_PASSWORD_REQUIRED',
  API_ERROR_USER_PASSWORD_INVALID = 'API_ERROR_USER_PASSWORD_INVALID',
  API_ERROR_USER_PASSWORDS_DO_NOT_MATCH = 'API_ERROR_USER_PASSWORDS_DO_NOT_MATCH',
  API_ERROR_USER_CURRENT_PASSWORD_WRONG = 'API_ERROR_USER_CURRENT_PASSWORD_WRONG',
  API_ERROR_USER_NOT_FOUND = 'API_ERROR_USER_NOT_FOUND',
  API_ERROR_USER_ACTIVE_REQUIRED = 'API_ERROR_USER_ACTIVE_REQUIRED',
  API_ERROR_USER_ACTIVE = 'API_ERROR_USER_ACTIVE',
  API_ERROR_USER_NOT_ACTIVE = 'API_ERROR_USER_NOT_ACTIVE',
  API_ERROR_USER_LOCK_REQUIRED = 'API_ERROR_USER_LOCK_REQUIRED',
  API_ERROR_USER_LOCK = 'API_ERROR_USER_LOCK',
  API_ERROR_USER_ROLES_EMPTY = 'API_ERROR_USER_ROLES_EMPTY',
  API_ERROR_USER_ROLE_NOT_FOUND = 'API_ERROR_USER_ROLE_NOT_FOUND',
  API_ERROR_REQUEST_PARAMETER_MISSING = 'API_ERROR_REQUEST_PARAMETER_MISSING',
  API_ERROR_REQUEST_METHOD_NOT_SUPPORTED = 'API_ERROR_REQUEST_METHOD_NOT_SUPPORTED',
  API_ERROR_REQUEST_MESSAGE_NOT_READABLE = 'API_ERROR_REQUEST_MESSAGE_NOT_READABLE',
  API_ERROR_REQUEST_PARAMETER_TYPE_MISMATCH = 'API_ERROR_REQUEST_PARAMETER_TYPE_MISMATCH',
  API_ERROR_INTERNAL_SERVER_ERROR = 'API_ERROR_INTERNAL_SERVER_ERROR',
}
