name: Spring Boot CI
run-name: ${{ github.actor }} started CI

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - backend/spring-boot/**
  pull_request:
    branches: [master]
    paths:
      - backend/spring-boot/**

jobs:
  build:
    defaults:
      run:
        working-directory: backend/spring-boot

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Build
        run: mvn -B clean install -DskipTests

      - name: Lint
        run: mvn -B spotless:check

      - name: Unit tests
        run: mvn -B test

      - name: Integration tests
        run: mvn -B failsafe:integration-test failsafe:verify
