name: Svelte Kit CI
run-name: ${{ github.actor }} started CI

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - frontend/svelte-kit/**
  pull_request:
    branches: [master]
    paths:
      - frontend/svelte-kit/**

env:
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  API_URL: ${{secrets.API_URL}}

jobs:
  build:
    defaults:
      run:
        working-directory: frontend/svelte-kit

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        run: pnpm run lint

      - name: Unit tests
        run: pnpm run test:unit

      - name: Integration tests
        run: |
          npx playwright install --with-deps
          npx playwright test --pass-with-no-tests
